# Generated by Django 4.1.7 on 2023-03-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logintable',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('l_email', models.CharField(max_length=150)),
                ('l_pass', models.CharField(max_length=50)),
                ('l_type', models.CharField(max_length=50)),
                ('l_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usertable',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_lname', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=100)),
                ('user_address', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_pass', models.CharField(max_length=100)),
                ('user_loca', models.CharField(max_length=100)),
                ('user1', models.CharField(default='', max_length=100)),
                ('user2', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
