# Generated by Django 4.1.7 on 2023-03-03 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_table',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_date', models.CharField(max_length=100)),
                ('cart_name', models.CharField(max_length=100)),
                ('cart_cat', models.CharField(max_length=100)),
                ('cart_stock', models.CharField(max_length=100)),
                ('cart_rate', models.CharField(max_length=100)),
                ('cart1', models.CharField(default='', max_length=100)),
                ('cart2', models.CharField(default='', max_length=100)),
                ('p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product_table')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usertable')),
            ],
        ),
    ]
