# Generated by Django 4.1.7 on 2023-03-17 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('feed2', models.CharField(default='', max_length=100)),
                ('feed', models.CharField(max_length=150)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usertable')),
            ],
        ),
    ]
