# Generated by Django 4.1.7 on 2023-03-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dboytable',
            fields=[
                ('dboyid', models.AutoField(primary_key=True, serialize=False)),
                ('dboy_name', models.CharField(max_length=100)),
                ('dboy_lname', models.CharField(max_length=100)),
                ('dboy_phone', models.CharField(max_length=100)),
                ('dboy_address', models.CharField(max_length=100)),
                ('dboy_email', models.CharField(max_length=100)),
                ('dboy_pass', models.CharField(max_length=100)),
                ('dboy_loca', models.CharField(max_length=100)),
                ('dboy1', models.CharField(default='', max_length=100)),
                ('dboy2', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
